"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams } from "next/navigation";
import { AccessGate } from "@/components/auth/AccessGate";
import apiClient from "@/lib/apiClient";
import {
  AlertCircle,
  CheckCircle2,
  Loader2,
  Save,
  Sparkles,
  RefreshCw,
  ArrowRight,
  ArrowLeft,
  Eye,
  EyeOff,
  Download,
  History,
  Zap,
  Info,
} from "lucide-react";
import Link from "next/link";

type CellMap = Record<string, Record<string, number>>;

interface MatrixSnapshot {
  timestamp: string;
  label: string;
  data: CellMap;
  pos: string[];
  nonzero: number;
}

function levelColor(v: number) {
  if (v === 3) return "bg-brand/80 text-white";
  if (v === 2) return "bg-brand/40 text-white";
  if (v === 1) return "bg-brand/15 text-white/70";
  return "bg-white/[0.03] text-white/20";
}

function levelLabel(v: number) {
  if (v === 3) return "High";
  if (v === 2) return "Med";
  if (v === 1) return "Low";
  return "None";
}

function relativeTime(iso: string) {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

const MATRIX_HISTORY_KEY = (courseId: string) => `co_po_matrix_history_${courseId}`;

function loadHistory(courseId: string): MatrixSnapshot[] {
  try {
    const raw = localStorage.getItem(MATRIX_HISTORY_KEY(courseId));
    if (!raw) return [];
    return JSON.parse(raw) as MatrixSnapshot[];
  } catch {
    return [];
  }
}

function saveHistory(courseId: string, snap: MatrixSnapshot) {
  try {
    const existing = loadHistory(courseId);
    const next = [snap, ...existing].slice(0, 5);
    localStorage.setItem(MATRIX_HISTORY_KEY(courseId), JSON.stringify(next));
  } catch {
    // ignore localStorage quota errors
  }
}

export default function COPOMatrixPage() {
  const params = useParams();
  const courseId = params.id as string;

  const [course, setCourse] = useState<any>(null);
  const [cosDetail, setCosDetail] = useState<any[]>([]);
  const [cosCodes, setCosCodes] = useState<string[]>([]);
  const [pos, setPos] = useState<string[]>([]);
  const [matrix, setMatrix] = useState<CellMap>({});
  const [savedMatrix, setSavedMatrix] = useState<CellMap>({});
  const [savedPos, setSavedPos] = useState<string[]>([]);
  const [savedAt, setSavedAt] = useState<string | null>(null);
  const [codeToId, setCodeToId] = useState<Record<string, string>>({});
  const [history, setHistory] = useState<MatrixSnapshot[]>([]);

  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [generatingLLM, setGeneratingLLM] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const [previewMode, setPreviewMode] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [showSaved, setShowSaved] = useState(false);
  const [generateMethod, setGenerateMethod] = useState<"semantic" | "llm">("llm");

  const matrixRef = useRef<HTMLDivElement>(null);
  const autoGeneratedRef = useRef(false);

  function buildEmpty(coList: string[], poList: string[]): CellMap {
    const m: CellMap = {};
    for (const co of coList) {
      m[co] = {};
      for (const po of poList) m[co][po] = 0;
    }
    return m;
  }

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    setSavedAt(null);
    setSavedPos([]);
    try {
      const [c, detail, matrixData] = await Promise.all([
        apiClient.getCourse(courseId),
        apiClient.getCourseOutcomesDetail(courseId),
        apiClient.getCOPOMatrix(courseId).catch(() => null),
      ]);
      setCourse(c);

      const fullCOs: any[] = Array.isArray(detail) ? detail : [];
      const coList: string[] = fullCOs.map((d: any) => String(d.code || "")).filter(Boolean);
      setCosDetail(fullCOs);
      setCosCodes(coList);

      const idMap: Record<string, string> = {};
      for (const d of fullCOs) idMap[String(d.code || "")] = String(d.id || "");
      setCodeToId(idMap);

      let poList: string[] = matrixData?.pos?.length > 0 ? matrixData.pos : [];
      if (poList.length === 0) {
        try {
          const nbaPOs = await apiClient.getNBAPOs();
          poList = Array.isArray(nbaPOs)
            ? nbaPOs.map((p: any) => String(p.code || p.id || "")).filter(Boolean)
            : [];
        } catch {
          poList = ["PO1", "PO2", "PO3", "PO4", "PO5", "PO6", "PO7", "PO8", "PO9", "PO10", "PO11", "PO12"];
        }
      }
      setPos(poList);

      const base = buildEmpty(coList, poList);
      if (matrixData?.data) {
        for (const co of coList) {
          for (const po of poList) {
            const v = matrixData.data[co]?.[po];
            if (typeof v === "number" && v > 0) base[co][po] = v;
          }
        }
      }
      setMatrix(base);

      if (matrixData?.pos?.length > 0 && matrixData?.data) {
        setSavedMatrix(matrixData.data as CellMap);
        setSavedPos(matrixData.pos);
        if (matrixData.saved_at) setSavedAt(matrixData.saved_at);
      }
    } catch (e: any) {
      setError(typeof e?.message === "string" ? e.message : "Failed to load matrix.");
    } finally {
      setLoading(false);
    }
  }, [courseId]);

  useEffect(() => {
    autoGeneratedRef.current = false;
    void load();
    setHistory(loadHistory(courseId));
  }, [load, courseId]);

  function cycleCell(co: string, po: string) {
    if (previewMode) return;
    setMatrix((prev) => ({
      ...prev,
      [co]: { ...prev[co], [po]: ((prev[co]?.[po] ?? 0) + 1) % 4 },
    }));
  }

  async function generateMatrix(methodOverride?: "semantic" | "llm", autoTriggered: boolean = false) {
    const methodToUse = methodOverride ?? generateMethod;
    if (methodToUse === "llm") setGeneratingLLM(true);
    else setGenerating(true);
    setError(null);
    if (!autoTriggered) setMessage(null);
    try {
      let result: any;
      if (methodToUse === "llm") {
        try {
          result = await apiClient.mapCOToPOWithLLM(courseId);
        } catch {
          // If LLM route fails, fall back to semantic mapping instead of leaving matrix blank.
          result = await apiClient.mapCOToPO(courseId, undefined, 0.1);
          result.method = "semantic_fallback";
        }
      } else {
        result = await apiClient.mapCOToPO(courseId, undefined, 0.1);
      }
      const count: number = result?.mappings_created ?? 0;
      const backendMethod = String(result?.method || (methodToUse === "llm" ? "llm" : "semantic"));
      const methodLabel = backendMethod === "llm"
        ? "AI (Ollama LLM)"
        : backendMethod === "semantic_fallback"
        ? "semantic fallback (LLM unavailable)"
        : "semantic similarity";
      const prefix = autoTriggered ? "Auto-generated" : "Matrix generated";
      setMessage(`${prefix} via ${methodLabel} - ${count} correlations mapped. Review values below and save.`);
      await load();
      setTimeout(() => matrixRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }), 300);
    } catch (e: any) {
      setError(typeof e?.message === "string" ? e.message : "Matrix generation failed.");
    } finally {
      setGenerating(false);
      setGeneratingLLM(false);
    }
  }

  const nonzero = cosCodes.reduce(
    (acc, co) => acc + pos.filter((po) => (matrix[co]?.[po] ?? 0) > 0).length,
    0,
  );
  const totalCells = cosCodes.length * pos.length;
  const density = totalCells > 0 ? nonzero / totalCells : 0;
  const densityOk = density >= 0.30 && density <= 0.60;

  useEffect(() => {
    if (loading || generating || generatingLLM || saving) return;
    if (cosCodes.length === 0) return;
    if (savedAt) return;
    if (nonzero > 0) return;
    if (autoGeneratedRef.current) return;

    autoGeneratedRef.current = true;
    void generateMatrix("llm", true);
  }, [loading, generating, generatingLLM, saving, cosCodes.length, savedAt, nonzero]);

  async function saveAll() {
    setSaving(true);
    setError(null);
    setMessage(null);
    try {
      const dept = String(course?.department || "").trim().toUpperCase();
      const programId = dept ? `DEPT:${dept}` : undefined;

      await Promise.all(
        cosCodes.map((co) => {
          const coId = codeToId[co];
          if (!coId) return Promise.resolve();
          const poCodes = pos.filter((po) => (matrix[co]?.[po] ?? 0) > 0);
          const poLevels: Record<string, number> = {};
          for (const po of poCodes) poLevels[po] = matrix[co][po];
          return apiClient.updateCOMappings(courseId, coId, {
            po_codes: poCodes,
            po_levels: poLevels,
            program_id: programId,
          });
        }),
      );

      const now = new Date().toISOString();
      const snap: MatrixSnapshot = {
        timestamp: now,
        label: `Saved ${new Date(now).toLocaleString()}`,
        data: JSON.parse(JSON.stringify(matrix)),
        pos: [...pos],
        nonzero,
      };
      saveHistory(courseId, snap);
      setHistory(loadHistory(courseId));
      setSavedMatrix(JSON.parse(JSON.stringify(matrix)));
      setSavedPos([...pos]);
      setSavedAt(now);
      setMessage("CO-PO matrix saved successfully.");
      setPreviewMode(true);
    } catch (e: any) {
      setError(typeof e?.message === "string" ? e.message : "Failed to save matrix.");
    } finally {
      setSaving(false);
    }
  }

  function restoreSnapshot(snap: MatrixSnapshot) {
    const base = buildEmpty(cosCodes, pos);
    for (const co of cosCodes) {
      for (const po of pos) {
        const v = snap.data[co]?.[po];
        if (typeof v === "number" && v > 0) base[co][po] = v;
      }
    }
    setMatrix(base);
    setMessage(`Restored matrix from ${relativeTime(snap.timestamp)}.`);
    setPreviewMode(false);
    setShowHistory(false);
  }

  const coStatements: Record<string, string> = {};
  for (const co of cosDetail) {
    coStatements[String(co.code || "")] = String(co.statement || co.co_statement || "");
  }

  return (
    <AccessGate feature="co_generation" deny="lock">
      <div className="w-full pb-24 space-y-6">
        <section className="border border-white/10 bg-gradient-to-r from-white/[0.04] to-white/[0.01] px-6 py-6">
          <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4">
            <div>
              <h1 className="text-3xl text-white font-display">CO-PO Correlation Matrix</h1>
              <p className="text-white/40 text-sm mt-1 font-mono">
                {course?.course_name || "Loading..."}
                {course?.course_code ? ` · ${course.course_code}` : ""}
              </p>
              <p className="text-white/30 text-xs mt-2">
                Generate with AI (Ollama), edit cells (0-1-2-3), save, then continue to exam configuration.
              </p>
            </div>
            <div className="flex items-center gap-3">
              <Link
                href={`/faculty/course/${courseId}/co-generation`}
                className="inline-flex items-center gap-1.5 px-3 py-2 border border-white/10 text-white/40 hover:text-white hover:border-white/30 text-xs font-mono uppercase tracking-widest transition-colors"
              >
                <ArrowLeft className="w-3 h-3" /> Back: COs
              </Link>
              <Link
                href={`/faculty/course/${courseId}/exam-config`}
                className="inline-flex items-center gap-1.5 px-4 py-2 border border-brand/40 text-brand hover:border-brand hover:text-white text-xs font-mono uppercase tracking-widest transition-colors"
              >
                Exam Config <ArrowRight className="w-3 h-3" />
              </Link>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 mt-5 border-t border-white/5 pt-4">
            {[
              ["COs", String(cosCodes.length)],
              ["POs", String(pos.length)],
              ["Mapped Cells", `${nonzero} / ${totalCells}`],
              ["Density", `${(density * 100).toFixed(0)}%`],
              ...(savedAt ? [["Last Saved", relativeTime(savedAt)] as [string, string]] : []),
            ].map(([label, value]) => (
              <div key={label} className="flex items-center gap-2">
                <span className="text-[10px] font-mono text-white/25 uppercase tracking-widest">{label}</span>
                <span
                  className={`text-xs font-mono ${
                    label === "Density"
                      ? density === 0
                        ? "text-white/30"
                        : densityOk
                          ? "text-attain"
                          : "text-amber-400"
                      : label === "Last Saved"
                        ? "text-white/50"
                        : "text-white"
                  }`}
                >
                  {value}
                </span>
              </div>
            ))}
            {density > 0 && !densityOk && (
              <span className="text-[10px] font-mono text-amber-400/60 flex items-center gap-1">
                <Info className="w-3 h-3" /> NBA target 30-60%
              </span>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2 mt-4 text-[10px] font-mono uppercase tracking-widest">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 border border-attain/40 text-attain">
              <CheckCircle2 className="w-3 h-3" /> 1. COs Ready
            </span>
            <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 border ${nonzero > 0 ? "border-attain/40 text-attain" : "border-white/10 text-white/30"}`}>
              {nonzero > 0 ? <CheckCircle2 className="w-3 h-3" /> : <Sparkles className="w-3 h-3" />} 2. Generate Matrix
            </span>
            <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 border ${savedAt ? "border-attain/40 text-attain" : "border-white/10 text-white/30"}`}>
              {savedAt ? <CheckCircle2 className="w-3 h-3" /> : <Save className="w-3 h-3" />} 3. Save
            </span>
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 border border-white/10 text-white/30">
              <ArrowRight className="w-3 h-3" /> 4. Exam Config
            </span>
          </div>
        </section>

        {error && (
          <div className="flex items-center gap-2 text-red-400 text-sm border border-red-500/30 bg-red-500/5 px-4 py-3">
            <AlertCircle className="w-4 h-4 shrink-0" /> {error}
          </div>
        )}
        {message && (
          <div className="flex items-center gap-2 text-emerald-400 text-sm border border-emerald-500/30 bg-emerald-500/5 px-4 py-3">
            <CheckCircle2 className="w-4 h-4 shrink-0" /> {message}
          </div>
        )}

        {loading ? (
          <div className="flex items-center gap-2 text-white/40 text-sm py-8">
            <Loader2 className="w-4 h-4 animate-spin" /> Loading matrix...
          </div>
        ) : cosCodes.length === 0 ? (
          <div className="py-12 text-center border border-white/10">
            <Sparkles className="w-8 h-8 text-white/10 mx-auto mb-3" />
            <p className="text-white/30 text-sm italic mb-4">No course outcomes found.</p>
            <Link
              href={`/faculty/course/${courseId}/co-generation`}
              className="inline-flex items-center gap-2 px-4 py-2 border border-brand/40 text-brand hover:border-brand text-xs font-mono uppercase tracking-widest"
            >
              <ArrowLeft className="w-3 h-3" /> Generate COs First
            </Link>
          </div>
        ) : (
          <>
            <section className="border border-white/10 bg-white/[0.015]">
              <div className="px-5 pt-5 pb-4">
                <div className="flex items-center gap-3 mb-4">
                  <Zap className="w-4 h-4 text-brand shrink-0" />
                  <div>
                    <h2 className="text-[10px] font-mono text-white/30 uppercase tracking-widest">Generate CO-PO Matrix with AI</h2>
                    <p className="text-xs text-white/35 mt-1">
                      AI assigns correlation levels (0-3) per CO x PO pair. Uses Ollama (local) for reasoning or semantic embeddings for speed.
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2 mb-5 pb-4 border-b border-white/5">
                  <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest mr-2">Method:</span>
                  {([
                    ["llm", "AI LLM (Ollama)", "Reason-based, best accuracy"],
                    ["semantic", "Semantic Similarity", "Embedding-based, faster"],
                  ] as [typeof generateMethod, string, string][]).map(([val, label, hint]) => (
                    <button
                      key={val}
                      onClick={() => setGenerateMethod(val)}
                      title={hint}
                      className={`px-3 py-1.5 border text-xs font-mono transition-colors ${
                        generateMethod === val
                          ? "border-brand text-brand bg-brand/10"
                          : "border-white/15 text-white/35 hover:border-white/30 hover:text-white/60"
                      }`}
                    >
                      {label}
                    </button>
                  ))}
                </div>

                <div className="flex items-center gap-3 flex-wrap">
                  <button
                    onClick={() => void generateMatrix()}
                    disabled={generating || generatingLLM || saving}
                    className="flex items-center gap-2 px-5 py-2.5 border border-brand/40 text-brand hover:border-brand hover:bg-brand/10 text-xs font-mono uppercase tracking-widest disabled:opacity-40 transition-colors"
                  >
                    {(generating || generatingLLM)
                      ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</>
                      : <><Sparkles className="w-3.5 h-3.5" /> Generate Matrix</>}
                  </button>

                  <button
                    onClick={() => void saveAll()}
                    disabled={saving || generating || generatingLLM || nonzero === 0}
                    className="flex items-center gap-2 px-5 py-2.5 border border-attain/40 text-attain hover:border-attain hover:bg-attain/10 text-xs font-mono uppercase tracking-widest disabled:opacity-40 transition-colors"
                  >
                    {saving
                      ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Saving...</>
                      : <><Save className="w-3.5 h-3.5" /> Save Matrix</>}
                  </button>

                  <button
                    onClick={() => setPreviewMode((v) => !v)}
                    disabled={nonzero === 0}
                    className={`flex items-center gap-2 px-4 py-2.5 border text-xs font-mono uppercase tracking-widest transition-colors disabled:opacity-40 ${
                      previewMode ? "border-white/30 text-white" : "border-white/15 text-white/40 hover:text-white hover:border-white/30"
                    }`}
                  >
                    {previewMode
                      ? <><EyeOff className="w-3.5 h-3.5" /> Edit Mode</>
                      : <><Eye className="w-3.5 h-3.5" /> Preview</>}
                  </button>

                  <button
                    onClick={() => void load()}
                    disabled={loading || generating || saving}
                    title="Reload from saved"
                    className="p-2.5 border border-white/10 text-white/30 hover:text-white hover:border-white/30 transition-colors disabled:opacity-40"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                  </button>

                  {history.length > 0 && (
                    <button
                      onClick={() => setShowHistory((v) => !v)}
                      className={`flex items-center gap-1.5 px-3 py-2.5 border text-xs font-mono uppercase tracking-widest transition-colors ${
                        showHistory ? "border-white/30 text-white" : "border-white/10 text-white/30 hover:text-white/60"
                      }`}
                    >
                      <History className="w-3.5 h-3.5" /> History ({history.length})
                    </button>
                  )}
                </div>
              </div>

              {nonzero > 0 && (
                <div className="border-t border-white/5 px-5 py-3 flex items-center gap-4">
                  <span className="text-[10px] font-mono text-white/25 uppercase tracking-widest">Density</span>
                  <div className="flex-1 h-1.5 bg-white/5 rounded-full overflow-hidden max-w-48">
                    <div
                      className={`h-full rounded-full transition-all ${densityOk ? "bg-brand" : density < 0.30 ? "bg-amber-500" : "bg-red-500"}`}
                      style={{ width: `${Math.min(100, density * 100)}%` }}
                    />
                  </div>
                  <span className={`text-xs font-mono ${densityOk ? "text-attain" : "text-amber-400"}`}>
                    {(density * 100).toFixed(0)}%
                  </span>
                  <span className="text-[10px] font-mono text-white/20">Target: 30-60%</span>
                </div>
              )}
            </section>

            {showHistory && history.length > 0 && (
              <section className="border border-white/10">
                <div className="px-5 py-4 border-b border-white/5 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <History className="w-3.5 h-3.5 text-white/40" />
                    <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest">Recent Matrices</span>
                  </div>
                  <span className="text-[10px] font-mono text-white/20">Restore any of the last 5 saves</span>
                </div>
                <div className="divide-y divide-white/5">
                  {history.map((snap, i) => {
                    const snapCells = Object.keys(snap.data).length * snap.pos.length;
                    const snapDensityPct = snapCells > 0 ? Math.round((snap.nonzero / snapCells) * 100) : 0;
                    return (
                      <div key={i} className="flex items-center justify-between px-5 py-3 hover:bg-white/[0.015]">
                        <div>
                          <p className="text-xs text-white/60">{snap.label}</p>
                          <p className="text-[10px] font-mono text-white/25 mt-0.5">
                            {snap.nonzero} cells mapped · {snapDensityPct}% density · {snap.pos.length} POs
                          </p>
                        </div>
                        <div className="flex items-center gap-3">
                          <span className="text-[10px] font-mono text-white/25">{relativeTime(snap.timestamp)}</span>
                          <button
                            onClick={() => restoreSnapshot(snap)}
                            className="px-3 py-1 border border-white/15 text-white/40 hover:text-white hover:border-white/40 text-xs font-mono transition-colors"
                          >
                            Restore
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </section>
            )}

            <div className="flex items-center gap-3 text-[10px] font-mono flex-wrap">
              {([
                [0, "0", "None"],
                [1, "1", "Low"],
                [2, "2", "Medium"],
                [3, "3", "High"],
              ] as [number, string, string][]).map(([v, label, desc]) => (
                <span key={v} className={`inline-flex items-center gap-1.5 px-3 py-1.5 border border-white/10 ${levelColor(v)}`}>
                  <span className="font-bold text-xs">{label}</span>
                  <span className="opacity-60">{desc}</span>
                </span>
              ))}
              {!previewMode && (
                <span className="text-white/20 ml-2">Click any cell to cycle 0 -&gt; 1 -&gt; 2 -&gt; 3</span>
              )}
              {previewMode && (
                <span className="text-white/30 ml-2 flex items-center gap-1.5">
                  <Eye className="w-3 h-3" /> Preview - click "Edit Mode" to modify
                </span>
              )}
            </div>

            <section ref={matrixRef} className="border border-white/10 overflow-x-auto">
              <table className="border-collapse text-xs font-mono w-full">
                <thead>
                  <tr className="bg-white/[0.02]">
                    <th className="sticky left-0 z-10 bg-[#0a1628] border-b border-r border-white/10 px-4 py-3 text-left text-[10px] text-white/30 uppercase tracking-widest whitespace-nowrap min-w-[140px]">
                      CO / PO
                    </th>
                    {pos.map((po) => (
                      <th key={po} className="border-b border-r border-white/10 px-2 py-3 text-center text-[10px] text-white/50 uppercase tracking-widest min-w-[52px]">
                        {po}
                      </th>
                    ))}
                    <th className="border-b border-white/10 px-3 py-3 text-center text-[10px] text-white/20 uppercase tracking-widest whitespace-nowrap">
                      Mapped
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {cosCodes.map((co) => {
                    const rowMapped = pos.filter((po) => (matrix[co]?.[po] ?? 0) > 0).length;
                    return (
                      <tr key={co} className="hover:bg-white/[0.015] transition-colors">
                        <td className="sticky left-0 z-10 bg-[#0a1628] border-b border-r border-white/10 px-4 py-2 align-middle">
                          <div>
                            <span className="text-brand font-semibold text-xs">{co}</span>
                            {coStatements[co] && (
                              <p className="text-[10px] text-white/25 leading-tight mt-0.5 max-w-[200px] truncate" title={coStatements[co]}>
                                {coStatements[co].slice(0, 55)}{coStatements[co].length > 55 ? "..." : ""}
                              </p>
                            )}
                          </div>
                        </td>
                        {pos.map((po) => {
                          const v = matrix[co]?.[po] ?? 0;
                          return (
                            <td
                              key={po}
                              onClick={() => cycleCell(co, po)}
                              title={`${co} x ${po} = ${v} (${levelLabel(v)})`}
                              className={`border-b border-r border-white/10 text-center select-none transition-all ${
                                previewMode ? levelColor(v) : `${levelColor(v)} cursor-pointer hover:ring-1 hover:ring-white/25`
                              }`}
                              style={{ width: 52, height: 42 }}
                            >
                              <span className="text-xs font-bold">{v}</span>
                            </td>
                          );
                        })}
                        <td className="border-b border-white/10 px-3 py-2 text-center text-[10px] font-mono text-white/30">
                          {rowMapped}/{pos.length}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr className="bg-white/[0.01]">
                    <td className="sticky left-0 bg-[#0a1628] border-t border-r border-white/10 px-4 py-2 text-[10px] font-mono text-white/25 uppercase tracking-widest">
                      PO Coverage
                    </td>
                    {pos.map((po) => {
                      const colMapped = cosCodes.filter((co) => (matrix[co]?.[po] ?? 0) > 0).length;
                      return (
                        <td key={po} className="border-t border-r border-white/10 px-2 py-2 text-center text-[10px] font-mono text-white/30">
                          {colMapped}/{cosCodes.length}
                        </td>
                      );
                    })}
                    <td className="border-t border-white/10 px-3 py-2 text-center text-[10px] font-mono text-white/40 font-bold">
                      {nonzero}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </section>

            {nonzero > 0 && !savedAt && (
              <div className="flex items-center justify-between gap-4 border border-amber-500/30 bg-amber-500/5 px-5 py-3">
                <div className="flex items-center gap-2 text-amber-400 text-xs font-mono">
                  <AlertCircle className="w-4 h-4 shrink-0" />
                  Matrix not yet saved - click Save Matrix to persist.
                </div>
                <button
                  onClick={() => void saveAll()}
                  disabled={saving}
                  className="shrink-0 flex items-center gap-2 px-4 py-2 border border-attain/40 text-attain hover:border-attain text-xs font-mono uppercase tracking-widest disabled:opacity-40 transition-colors"
                >
                  {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
                  Save Matrix
                </button>
              </div>
            )}

            {savedPos.length > 0 && (
              <section className="border border-white/10">
                <button
                  onClick={() => setShowSaved((v) => !v)}
                  className="w-full flex items-center justify-between px-5 py-4 hover:bg-white/[0.02] transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <Eye className="w-3.5 h-3.5 text-white/40 shrink-0" />
                    <div className="text-left">
                      <p className="text-[10px] font-mono text-white/30 uppercase tracking-widest">Saved Matrix Preview</p>
                      {savedAt && (
                        <p className="text-[10px] font-mono text-white/20 mt-0.5">
                          Last saved {relativeTime(savedAt)} · {savedPos.length} POs mapped
                        </p>
                      )}
                    </div>
                  </div>
                  <span className="text-[10px] font-mono text-white/20">{showSaved ? "Hide ^" : "Show v"}</span>
                </button>

                {showSaved && (
                  <div className="border-t border-white/5 overflow-x-auto">
                    <table className="border-collapse text-xs font-mono w-full">
                      <thead>
                        <tr className="bg-white/[0.01]">
                          <th className="sticky left-0 bg-[#0a1628] border-b border-r border-white/10 px-4 py-2 text-left text-[10px] text-white/20 min-w-[120px]">
                            CO / PO
                          </th>
                          {savedPos.map((po) => (
                            <th key={po} className="border-b border-r border-white/10 px-2 py-2 text-center text-[10px] text-white/25 min-w-[52px]">
                              {po}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {cosCodes.map((co) => (
                          <tr key={co} className="hover:bg-white/[0.01]">
                            <td className="sticky left-0 bg-[#0a1628] border-b border-r border-white/10 px-4 py-2 text-white/35 whitespace-nowrap text-xs">
                              {co}
                            </td>
                            {savedPos.map((po) => {
                              const v = (savedMatrix[co]?.[po] as number) ?? 0;
                              return (
                                <td
                                  key={po}
                                  className={`border-b border-r border-white/10 text-center ${levelColor(v)}`}
                                  style={{ width: 52, height: 38 }}
                                >
                                  {v}
                                </td>
                              );
                            })}
                          </tr>
                        ))}
                      </tbody>
                    </table>

                    <div className="px-5 py-3 border-t border-white/5 flex items-center justify-between">
                      <p className="text-[10px] font-mono text-white/20">
                        This is the persisted state. Edit the matrix above and save to update.
                      </p>
                      <button
                        onClick={() => {
                          const rows = ["CO/PO," + savedPos.join(",")];
                          for (const co of cosCodes) {
                            rows.push([co, ...savedPos.map((po) => String(savedMatrix[co]?.[po] ?? 0))].join(","));
                          }
                          const blob = new Blob([rows.join("\n")], { type: "text/csv" });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement("a");
                          a.href = url;
                          a.download = `co_po_matrix_${courseId}.csv`;
                          a.click();
                          URL.revokeObjectURL(url);
                        }}
                        className="flex items-center gap-1.5 px-3 py-1.5 border border-white/10 text-white/30 hover:text-white hover:border-white/30 text-xs font-mono transition-colors"
                      >
                        <Download className="w-3 h-3" /> Export CSV
                      </button>
                    </div>
                  </div>
                )}
              </section>
            )}

            {savedAt && densityOk && (
              <div className="flex items-center justify-between gap-4 border border-attain/30 bg-attain/5 px-5 py-4">
                <div>
                  <div className="flex items-center gap-2 text-attain text-xs font-mono mb-1">
                    <CheckCircle2 className="w-4 h-4" /> CO-PO matrix saved - density within NBA range ({(density * 100).toFixed(0)}%).
                  </div>
                  <p className="text-xs text-white/40">Proceed to exam configuration to set up assessments for attainment calculation.</p>
                </div>
                <Link
                  href={`/faculty/course/${courseId}/exam-config`}
                  className="shrink-0 inline-flex items-center gap-2 px-5 py-2.5 border border-attain/60 text-attain hover:border-attain hover:bg-attain/10 text-xs font-mono uppercase tracking-widest transition-colors"
                >
                  Exam Config <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            )}
          </>
        )}
      </div>
    </AccessGate>
  );
}
